#!/bin/bash
total 4
drwxr-xr-x 4 root root  60 Jul  5 15:40 .
drwxr-xr-x 1 root root 163 Jul  5 15:34 ..
drwxr-xr-x 2 root root 139 Jul  5 17:09 0x00-shell_basics
drwxr-xr-x 8 root root 166 Jul  5 17:10 .git
-rw-r--r-- 1 root root   8 Jul  5 15:44 README.md
